version: "3.8"

services:
  spring-mysql:
    image: mysql
    container_name: spring-mysql
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD:${MYSQL_ROOT_PASSWORD}:password
    ports:
      - "3317:3306"
    volumes:
      - ./data:/var/lib/mysql
    networks:
      spring-database-network:

  spring-adminer:
    image: adminer
    container_name: spring-adminer
    restart: always
    depends_on:
      - spring-mysql
    ports:
      - '8081:8080'
    networks:
      spring-database-network:

  spring-app:
    image: spring-app:v9
    container_name: spring-app
    restart: on-failure
    depends_on:
      - spring-mysql
    ports:
      - '8001:8000'
    networks:
      spring-database-network:

networks:
  spring-database-network: